theme: jekyll-theme-minimal
title: Mohan Kumar
description: "Research Scientist at Meta Reality Labs specializing in machine learning acceleration and SIMD vectorization."
email: mohan.cbein@gmail.com
show_downloads: false
google_analytics: G-XBGZYNNC5D
avatar: "/data/mohan_new.jpeg"
github_username: mohankku